---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: api-gw-lambda-load-test-001/02-dynamodb

Resources:
  DataTable:
    Type: AWS::Serverless::SimpleTable

  SsmParameterDataTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /api-gw-lambda-load-test/001/DataTableName
      Type: String
      Value: !Ref DataTable
